### ISSUE TITLE
Find solution for the “Geminated El”

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif-pro#15]
See: http://www.l·l.cat/info/the-geminated-el

**Comment by frankrolf** [comment]
This could be solved via language-aware contextual GSUB, or contextual GPOS.

**Comment by miguelsousa** [comment]
I think you don't even need to make the contextual GSUB language-aware, if you include the second L in the context.

**Comment by frankrolf** [comment]
@miguelsousa  I have been thinking about that, I wonder how many people would “decorate” type like this: `·h·e·l·l·o·`.
Edge case or eBay feedback?

**Comment by miguelsousa** [comment]
Those people MUST get the geminated L.

**Comment by khaledhosny** [comment]
Don’t they use middle dot in dictionaries to indicate hyphenation?

**Comment by frankrolf** [comment]
No, the middle dot is used to indicate a two-syllable word, such as `instal·lacion`. Without the dot, the `ll` would be pronounced similar to j, as in `relleno`. Since the middle dot is easy to access on the keyboard, it has become the standard approach (sometimes, you’ll also see the period being used).

**Comment by frankrolf** [comment]
I may have misread the “they”:
In dictionaries, I feel like the bullet character is more commonly used between syllables.

**Comment by fitojb** [comment]
The interpunct we use for _l·l_ is U+00B7. For dictionary usage, U+2027 should be used.

**Comment by frankrolf** [comment]
https://github.com/adobe-fonts/source-code-pro/issues/192

**Comment by frankrolf** [comment]
I decided to address this through contextual kerning.
I also decided to not hide that kerning behind a language tag – the combination is fairly unique. This makes bugs like adobe-fonts/source-code-pro#192 possible, but I believe this edge case is outweighed by the usefulness of this solution for Catalan text.

I wrote a script which basically mimics the composition & advance width of the (obsolete, but nevertheless present in the UFOs) ldot glyph, when `l` `·` `l` are typed.

The script is here:
https://gist.github.com/frankrolf/9648335ddcf624edc3d79aebea67e3e7

**Comment by frankrolf** [comment]
In the latest release of Source Serif, the combination `l` `·` `l` will now automatically reposition the centered period for a more even word image.
Please report back in case of unexpected/suboptimal behavior!

https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.007R-ro%2F1.007R-it
