### ISSUE TITLE
Add Bulgarian Cyrillic letter forms

### ISSUE THREAD

**Issue by ignisf** [adobe-fonts/source-serif-pro#20]
Hello,

I am opening this issue as a follow-up of https://github.com/adobe-fonts/source-serif-pro/issues/4#issuecomment-233499726.

The Bulgarian letter forms through the use of `locl` are still a desired feature.

Thank you for the great work!

**Comment by frankrolf** [comment]
Yes! I love Bulgarian Cyrillic and have already warned [Krista Radoeva](http://kristaradoeva.com) I’d ask her for help! 🇧🇬

**Comment by ignisf** [comment]
https://github.com/adobe-fonts/source-serif-pro/compare/264fa7b241...460a85cc40 cc @stefanpeev *it's happening* ^_^

**Comment by frankrolf** [comment]
Bulgarian (and Serbian/Macedonian) alternates for both Roman and Italic are available in release 3.0:
https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.000R
