### ISSUE TITLE
Add OTMath version: Source Serif Pro Math

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-serif-pro#23]
To make this font work for academic papers!

**Comment by frankrolf** [comment]
You brought this up earlier (#13), and I responded accordingly, so I hope you don’t mind me closing this.

**Comment by ShikiSuen** [comment]
@be5invis One thing you need to learn is that do not expect your feature requests to Frank's post be applied on time. I am afraid if I recommend you to use other fonts instead then I will be blamed by Frank again for "lack of respect". Last time I recommend italic-font-appealers in this bug tracker to use other fonts instead, and Frank's response made Ken Lunde blamed me. These celebrities' words could be extremely harmful, and they would absolutely not take their misspoken words back.

@miguelsousa Please lock this issue as what you did last time, thanks.

**Comment by ShikiSuen** [comment]
I apologize for my reply above all because what happened here triggered my trauma again. I won't remove that reply this time but I did edited it for fixing some misspelled words.

**Comment by frankrolf** [comment]
@ShikiSuen I honestly don’t understand what you are upset about. Please try to see those requests from our perspective as well – many users simply underestimate the amount of research, design work, proofing and production involved in a typeface design.
What do you mean with “applied on time”? Whose timeline are we supposed to follow?

Our team is small, and we may get to fixing one major issue or another, but certainly can’t address all of them. In the related issue #13, I asked for support with research and purpose of mathematical symbols (which is a minor thing to could ask) – but so far, nothing has happened.

**Comment by ShikiSuen** [comment]
@frankrolf No one is urging you to finish this repo faster prior to your paid mandatory jobs. Do not put your dirty cap on my head. I just suggest appealers to use other solutions for a while. What are you worrying about?

**Comment by frankrolf** [comment]
@ShikiSuen I am worrying about you not understanding the nature of our projects. It seems you sometimes don’t realize the scope of your requests..
Be assured we all work on those projects more than our _paid mandatory jobs_ require. 
Commenting on a closed duplicate issue does not seem to be a constructive way to help this project.

**Comment by ShikiSuen** [comment]
@frankrolf Thanks for your patience this time. I forgot to answer your questions.

1. [What do you mean with “applied on time”?]
It is solely up to you. However I don't understand why my suggestion to appealers here regarding using alternative products for a while could make you so upset. Last time I did this and both you and Ken think that I am disrespecting your labor pressure, putting me as an aiming target of your followers' rage. What I said "on time" is to not let people wait for too long time. Considering the nature of your projects, if I were you I would suggest them to use alternative products and come back only when updates were officially announced.

2. [Whose timeline are we supposed to follow?]
Yours.

**Comment by frankrolf** [comment]
Thanks for the clarification.

**Comment by ShikiSuen** [comment]
@frankrolf Thanks for your consideration this time. Too lucky that we end the argument here prior to others' replies.

**Comment by ShikiSuen** [comment]
Oh sorry for my bad English. I should use "so lucky" instead in my previous reply. Fixed.
