### ISSUE TITLE
Anchors in M are missing in the light master

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif-pro#27]

**Comment by miguelsousa** [comment]
This is already fixed in the **variable-fonts** branch. This branch will be merged with master very soon.

**Comment by frankrolf** [comment]
Let’s close this when the branch is actually merged, and new fonts with the missing anchors ship. I created this bug mainly as a reminder for myself, so it’s better to have it in the “to do” list.

**Comment by frankrolf** [comment]
Fixed in latest release: 
https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.007R-ro%2F1.007R-it
