### ISSUE TITLE
"RT" looks bad

### ISSUE THREAD

**Issue by fefe17** [adobe-fonts/source-serif-pro#29]
One of my font test phrases is "VARTA" (it's the name of a battery brand)

![varta](https://user-images.githubusercontent.com/17782616/29967242-04ae1572-8f16-11e7-8063-3049ca49b9e1.png)

The word looks very uneven, in particular between the R and the T. See screenshot (from Firefox on Linux)

**Comment by frankrolf** [comment]
This looks like some unfortunate rasterization coincidence. Does it look the same in other browsers? Can you provide more information, such as font version used, text size, etc.

Attached is a PDF in which you will see the built-in spacing of the word in all styles – I don’t see a way to change it significantly.
My advice – track out the paragraph if you are setting smaller text like this.
[VARTA.pdf](https://github.com/adobe-fonts/source-serif-pro/files/1271079/VARTA.pdf)

**Comment by adrientetar** [comment]
There might be kerning on that pair, make sure you have `font-feature-settings: "kern", "liga";` in the css.

**Comment by frankrolf** [comment]
There is kerning, -31 units for the R T combination. I wonder if this example has been over-kerned somehow?
<img width="1112" alt="screen shot 2017-09-01 at 11 30 48" src="https://user-images.githubusercontent.com/2049645/29983065-02c7e6d2-8f09-11e7-99dc-ecc9e240377a.png">
