### ISSUE TITLE
Draw the overlaps in a way that avoids spikes

### ISSUE THREAD

**Issue by miguelsousa** [adobe-fonts/source-serif-pro#31]
If possible, draw the overlaps in a way that avoids spikes when the font is stroked. This problem only happens with the variable font version.

Issue originally posted at https://forums.adobe.com/message/9937181
<img width="1059" alt="screen shot 2017-11-01 at 18 35 07" src="https://user-images.githubusercontent.com/2119742/32305562-82375bd2-bf33-11e7-9c18-7de647602c5d.png">

**Comment by frankrolf** [comment]
This can be avoided by setting the miter limit of the stroke to a smaller value. The standard is 4, 3 or 2 works for me.

**Comment by miguelsousa** [comment]
@frankrolf yes, the OP mentioned that. But if reducing how much the overlaps extend beyond the crossing point is easy enough, then let's do it and get this fixed for the people that use the defaults (which is almost everyone). 👌?

**Comment by frankrolf** [comment]
Yes, I plan to simplify the point structure in many glyphs with overly-complex construction.

**Comment by frankrolf** [comment]
I addressed this in several glyphs (as indicated in the original screenshot, and a few more). That said, this largely is a theoretical problem which can’t really be solved in a satisfactory fashion on my end – it all depends on the stroke width used, and the miter limit set.
At any rate, the effect seen above should now be minimized.

**Comment by frankrolf** [comment]
The latest release takes care of this problem in many glyphs.
It will take a while until the variable fonts make it into Illustrator and other applications, but you can try out the new variable fonts (1.011 Roman/1.001 Italic) today:
https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.007R-ro%2F1.007R-it

Please report back if you still see spikes when outlining glyphs.
