### ISSUE TITLE
Wrong extensions with italics release

### ISSUE THREAD

**Issue by Wolfr** [adobe-fonts/source-serif-pro#34]
I think something went wrong with the release, I downloaded the fonts and they all have .woff2 extensions, even the ones in the OTF TTF folders. If I rename the files I can see the TTFs/OTFs.

<img width="513" alt="screen shot 2018-08-18 at 12 48 43" src="https://user-images.githubusercontent.com/12690/44298535-46923e80-a2e5-11e8-8cac-ff4cd1e4cc28.png">

Just reporting this!

**Comment by frankrolf** [comment]
It is possible to create WOFF/WOFF2 files from both OTF and TTF files. This is why there are subfolders within the WOFF/WOFF2 folders (the main difference is size).
In the root folder of the archive, there should be flat TTF/OTF folders, too!
