### ISSUE TITLE
Small Caps: ß is rendered as SS

### ISSUE THREAD

**Issue by SFr682k** [adobe-fonts/source-serif-pro#35]
Using the latest release of Source Serif Pro, the sharp s (ß) used in German language is rendered as SS when using the small caps shape. However, I would welcome using a “scaled down” version of the uppercase sharp s (ẞ) such as Source Sans Pro does:
  
![Comparison: Small Caps ß, in Source Serif Pro and Source Sans Pro](https://user-images.githubusercontent.com/23553692/44431126-360bed80-a59d-11e8-8777-74900da7e757.png)

**Comment by miguelsousa** [comment]
Two esses is the correct capitalization of ß, so applying `smcp` to the word **Straßenschild** should render as **STRASSENSCHILD** (two esses) not **STRA&#x1E9E;ENSCHILD** (capital sharp s).

The correct way to get a small cap variant of &#x1E9E; (U+1E9E) is by applying `c2sc` to a word containing this character.

**Comment by SFr682k** [comment]
Actually, both variants are equally valid since June 2017 (see this [Wikipedia article](https://en.wikipedia.org/wiki/Capital_ß))  
The reason why I prefer rendering as STRAẞENSCHILD (with capital sharp s) is, that it keeps words with different meanings, such as „Maß“ and „Mass“, distinguishable in their small caps form.

**Comment by frankrolf** [comment]
Since both variants are equally valid, this is not an issue.
The SS-solution will be more familiar to most users, those who really want the capital variant will know how to get to it.
