### ISSUE TITLE
Release CSS references missing EOT files

### ISSUE THREAD

**Issue by davidmerfield** [adobe-fonts/source-serif-pro#39]
Hello! Thank you all for the Source typefaces.

In the zip attached to the latest release, the file ```source-serif-pro.css``` references EOT files which do not exist:

```css
...
    src: url('EOT/SourceSerifPro-ExtraLight.eot') format('embedded-opentype'),
...
```

The zip contains OTF, TTF, VAR, WOFF and WOFF2 directories, but not an EOT directory. Looks like [build.sh](/build.sh) needs to be amended somehow.

**Comment by frankrolf** [comment]
Thanks for the note – the release zip file points to a commit before this happened: 
https://github.com/adobe-fonts/source-serif-pro/commit/edf1db28d8ff4a9cf1edead9f8c5cfc87c519173

Not removing EOT (which has been deprecated and will no longer be distributed as part of this repository) was an oversight on my part, but not worth making a new release for IMO.
