### ISSUE TITLE
Add Greek, Cyrillic and IPA support

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-serif-pro#4]
I'm wondering there is a high quality Serif font which covers full LGC characters and IPA.
Providing MARK and MKMK support will be nicer.

**Comment by prodelay** [comment]
Any progress? Is it still developed?

**Comment by frankrolf** [comment]
Yes, this is still in development.

**Comment by prodelay** [comment]
Thanks, that is encouraging! Good luck! :+1:

**Comment by ignisf** [comment]
Please note the discussion here when implementing the Cyrillic subset: https://github.com/googlei18n/noto-fonts/issues/89

**Comment by pauldhunt** [comment]
@ignisf i would be very happy to add Bulgarian Cyrillic to the Source fonts if there are any designers who would like to contribute these shapes to the repertoire. Will you do this? 😄

**Comment by miguelsousa** [comment]
Nice [blog post on Cyrillic letter forms](http://www.fontsmith.com/blog/2016/10/12/cyrillic-script-variations-and-the-importance-of-localisation), by Krista Radoeva.

**Comment by frankrolf** [comment]
@be5invis Greek and Cyrillic are part of [Version 2.0](https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.000R), which also adds `mark` and `mkmk` support.

I would like to encourage you to open a new issue if IPA support is still desired. Thanks!
