### ISSUE TITLE
Allow double-stacked combining accents

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-serif-pro#42]
This combination appeared in a Bible translated in Jian’ou dialect of Min Chinese.
![Sample](https://upload.wikimedia.org/wikipedia/commons/1/1b/JianningBible1.gif)
However it doesn’t work well with Source Serif Pro.
>ā̄ē̄ī̄ō̄ū̄

![screenshot](https://user-images.githubusercontent.com/10364351/49958227-14df5c00-ff02-11e8-9d0b-67eb473e8426.PNG)
See: https://books.google.com/books?id=WCYMAwAAQBAJ&pg=PA559&lpg=PA559&dq=kienning+romanized&source=bl&ots=F7RIDpm5PW&sig=P0cHBakCJK0EOemLoy6GgIYi_74&hl=en&sa=X&ei=4f7sVJSrA9Xv8gXCtIKoAw&ved=0CC4Q6AEwBA#v=onepage&q=kienning%20romanized&f=false

**Comment by frankrolf** [comment]
Mark feature support in Source Serif has been experimental, so it is good that bugs like this one are filed. Thank you!
The scenario described is similar to the closed bug #41 above, I decided to track both enhancement requests together here.

**Comment by frankrolf** [comment]
<img width="701" alt="Screen Shot 2019-05-19 at 18 05 42" src="https://user-images.githubusercontent.com/2049645/57984937-e5a8ba00-7a60-11e9-9f1a-da9be5c4a4fd.png">

**Comment by frankrolf** [comment]
Stacked combining accents should work as of version 3.0 (released today) – please let me know if there are any more issues!
