### ISSUE TITLE
Italics on Google Fonts

### ISSUE THREAD

**Issue by chasemccoy** [adobe-fonts/source-serif-pro#43]
From what I can tell in the release notes, the Italic variants have been out for quite a while, yet they're not on Google Fonts. I was curious if this was for any particular reason, or have they just not been added yet? It would be great to get them up there!

**Comment by miguelsousa** [comment]
No particular reason from our part. You should log the issue with them.

They're available on [Adobe Fonts](https://fonts.adobe.com/fonts/source-serif), in case it helps.

**Comment by evnbr** [comment]
I pinged Google Fonts as well, but curious if there's any update on the Adobe side to get italics included?
