### ISSUE TITLE
underscore (U+005F) not visible in .pdf when using TTF

### ISSUE THREAD

**Issue by theovanh** [adobe-fonts/source-serif-pro#44]
Underscore (ascii 5F) is not visible when a document in Word 2007 is saved as .pdf Other fonts do not have this problem. The character '5F' is present in the .pdf but not visible. Windows 10.
![image](https://user-images.githubusercontent.com/3441430/50335449-a86cea00-050b-11e9-90fb-8e294fc35c1c.png)

**Comment by frankrolf** [comment]
That’s odd. Which version of the font are you using? OTF or TTF?
At first glance it looks similar to this problem: https://github.com/adobe-fonts/source-sans-pro/issues/154

Would like to get to the bottom of this, but I don’t know if there’s anything one can do in the font files. Please try the TTF if you are using OTF, and vice versa.

**Comment by frankrolf** [comment]
How is the PDF generated? You may want to try using the Adobe PDF “printer”:
https://helpx.adobe.com/acrobat/using/print-to-pdf.html

**Comment by theovanh** [comment]
I made the .pdf by Save as… in Word 2007. So it is a Word document saved by the pdf-save function in Word 2007.

 

Striking is that the omission of the display of the underscore (ascii 5F) only happens with the Source Serif Pro font as demonstrated by the example that I attached. I am disappointed because I like the font very much.

 

As I explained, the character is actually present in the .pdf. This is demonstrated by selecting a piece of text in the .pdf , then copy and paste into Notepad where the underscore shows up.

 

Opening the .pdf with Firefox, Chrome, MS Edg e makes nog difference. None of these shows the underscore, not with Source Serif Pro of Source Serif Pro Semibold.

 

There must be something in the code of the font.

 

I do hope , this bug  can be removed.

 

Success, hope to hear from you,

Theo van Herwijnen

 

Van: Frank Grießhammer [mailto:notifications@github.com] 
Verzonden: Friday, December 21, 2018 12:06 PM
Aan: adobe-fonts/source-serif-pro
CC: theovanh; Author
Onderwerp: Re: [adobe-fonts/source-serif-pro] underscore (ascii 5F) not visible in .pdf (#44)

 

How is the PDF generated? You may want to try using the Adobe PDF “printer”:
https://helpx.adobe.com/acrobat/using/print-to-pdf.html

**Comment by theovanh** [comment]
Frank,

 

Quick answer: I use the TTF. Tomorrow I will test the OTF.

 

Regards,

Theo

 

Van: Frank Grießhammer [mailto:notifications@github.com] 
Verzonden: Friday, December 21, 2018 11:54 AM
Aan: adobe-fonts/source-serif-pro
CC: theovanh; Author
Onderwerp: Re: [adobe-fonts/source-serif-pro] underscore (ascii 5F) not visible in .pdf (#44)

 

That’s odd. Which version of the font are you using? OTF or TTF?
At first glance it looks similar to this problem: adobe-fonts/source-sans-pro#154 <https://github.com/adobe-fonts/source-sans-pro/issues/154> 

Would like to get to the bottom of this, but I don’t know if there’s anything one can do in the font files. Please try the TTF if you are using OTF, and vice versa.

**Comment by theovanh** [comment]
The font file is version 2.007; hotconv 1.0.1.08;makeotfexe 2.5.65593.
I believe the problem is rather with the Reader Reader XI, version 11.0.23. Upgraded to Reader DC 2019.010.20064 and repeated the exercise : underscore is carried through into Notepad but not shown in Reader DC:

![image](https://user-images.githubusercontent.com/3441430/50373619-1c79c180-05e2-11e9-9d48-c1f10eba7c5b.png)

**Comment by frankrolf** [comment]
@theovanh Would you mind trying to write the PDF in another way – not through “save as…” but using the Adobe PDF printer. I’d be curious to know the result here.

**Comment by theovanh** [comment]
I do not have the Acrobat virtual printer available. I printed with 'cutePDFWriter' which gave me a .pdf where the underscores are visible in Reader DC. When 'printed' from Word with 'Microsoft Print to PDF' the result did NOT show the underscore of Source Serif Pro but copy/paste into Notepad demonstrated that they are present (as in the test above). Probably the 'MS Print to PDF' uses the same function as its 'Save as ..' 
Conclusion: the problem is caused by the Word 2007 PDF software which makes Reader DC refuse to show the 5F underscore in font Source Serif Pro.

**Comment by theovanh** [comment]
Frank,

 

Good morning.

I posted on github my latest findings. Attached the 2 pdf’s. I noticed that there are significant differences in the Properties/Fonts of the 2 pdf’s.

 

Succes,

Theo

 

 

Van: Frank Grießhammer [mailto:notifications@github.com] 
Verzonden: Friday, December 21, 2018 12:06 PM
Aan: adobe-fonts/source-serif-pro
CC: theovanh; Author
Onderwerp: Re: [adobe-fonts/source-serif-pro] underscore (ascii 5F) not visible in .pdf (#44)

 

How is the PDF generated? You may want to try using the Adobe PDF “printer”:
https://helpx.adobe.com/acrobat/using/print-to-pdf.html

**Comment by frankrolf** [comment]
Dear Theo, happy new year!
Unfortunately I did not personally receive the PDFs you promised (all messages are re-routed through GitHub and attachments removed)
Could you please send them again directly at fgriessh@adobe.com – thank you!

**Comment by frankrolf** [comment]
Also reproduced, analog to https://github.com/adobe-fonts/source-sans-pro/issues/154#issuecomment-451433797:

Step-by-step:
- install Source Serif Pro Regular 2.007 TTF
- create new Word document in MS Word 2016 on Windows 10.
- paste the text `Function __construct($first_name, $last_name)`

## option 1
File → Save as… → PDF
result: underscores are missing from PDF
## option 2
File → Print → Microsoft Print to PDF
result: underscores are missing from PDF
## option 3
File → Save as Adobe PDF …
no text whatsoever in PDF

## workaround
All above options work properly when using the equivalent OTF font.

**Comment by miguelsousa** [comment]
Fixed in this release https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.010R-ro%2F1.010R-it
