### ISSUE TITLE
Romans support Greek & Cyrillic support  whereas Italics don't

### ISSUE THREAD

**Issue by cssobral2013** [adobe-fonts/source-serif-pro#45]

**Comment by frankrolf** [comment]
This is expected, and one of the reasons why the version numbers differ between Roman and Italic.
Work on Italics started after the first versions of the Romans had been released, you can read more about the development of the Italics here: https://blog.typekit.com/2018/08/16/source-serif-italics/

That said, work on achieving feature parity between Romans and Italics is in progress, as seen in the `greek-italic` branch.

**Comment by frankrolf** [comment]
Officially fixed with 3.0 release: https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.000R
