### ISSUE TITLE
Ukrainian її

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif-pro#48]
The Ukrainian word її (“her”) is insufficiently supported in Source Serif. Solutions include tighter spacing of the diaeresis, or triple-dotting this particular case (instead of four dots).
Some in-use here: https://uk.wikipedia.org/wiki/Її_як_і_раніше_переслідує_негідник

![screen shot 2019-01-28 at 13 55 25](https://user-images.githubusercontent.com/2049645/51837679-669e4300-2304-11e9-90e2-f962057478d6.png)

**Comment by moyogo** [comment]
If possible, the same should be done for the Latin ïï which may occur in some orthographies like Beli (https://beli.webonary.org/browse/beli-english/?letter=b&key=qaa-Latn-SD-x-jur with bïï “dog”) or Tiriyó (in http://etnolinguistica.wdfiles.com/local--files/tese%3Ameira-1999/meira_1999_tiriyo.pdf with mïïna “grumble”, pïï “mountain”, wïïse “lipstick tree”).

**Comment by frankrolf** [comment]
Good to know! Thanks.

**Comment by frankrolf** [comment]
![2019-05-16_134119](https://user-images.githubusercontent.com/2049645/57851227-542b1500-77e0-11e9-9875-77d92985d3a2.png)

**Comment by frankrolf** [comment]
Implemented (for both Latin and Cyrillic) in Release 3.0:
https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.000R
