### ISSUE TITLE
Italic Greek and Cyrillic

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-serif-pro#51]
A follow-up for #2.

**Comment by frankrolf** [comment]
For Greek, see #37.

**Comment by frankrolf** [comment]
Cyrillic is in progress, and something visible should surface soon.

**Comment by frankrolf** [comment]
This work has been completed with the release of version 3.000:
https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.000R
