### ISSUE TITLE
GSUB input glyphs do not have matching output

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-serif-pro#53]
all Romans:
12 unmatched contextual input(s)
  Lcaron in 'ccmp' feature
  Ldot in 'ccmp' feature
  Uogonek in 'ccmp' feature
  aogonek in 'ccmp' feature
  dcaron in 'ccmp' feature
  eogonek in 'ccmp' feature
  uni0123 in 'ccmp' feature
  i.trk in 'ccmp' feature
  lcaron in 'ccmp' feature
  ldot in 'ccmp' feature
  tcaron in 'ccmp' feature
  uogonek in 'ccmp' feature

all Italics:
13 unmatched contextual input(s)
  Lcaron in 'ccmp' feature
  Ldot in 'ccmp' feature
  Uogonek in 'ccmp' feature
  aogonek in 'ccmp' feature
  dcaron in 'ccmp' feature
  eogonek in 'ccmp' feature
  uni0123 in 'ccmp' feature
  iogonek in 'ccmp' feature
  i.trk in 'ccmp' feature
  lcaron in 'ccmp' feature
  ldot in 'ccmp' feature
  tcaron in 'ccmp' feature
  uogonek in 'ccmp' feature

**Comment by frankrolf** [comment]
Fixed. This had to do with this line:
`sub [ @LAT_UC_ACCENTED @LAT_LC_ACCENTED ]' lookup DECOMPOSITION @MARKS_CMB;`

Some of the glyphs in either of those two classes (such as Ldot) had no clearly indicated decomposition rule in the DECOMPOSITION lookup, which results in the error above.

**Comment by erniemarch** [comment]
checked in build 2.940. Fixed.
