### ISSUE TITLE
lowercase 'i' in 'ordn' and 'sups' not scaling for some languages

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-serif-pro#54]
lowercase 'i' in ordn/AZE, sups/AZE, ordn/CRT, sups/CRT, ordn/TRK, sups/TRK  not scaling

**Comment by frankrolf** [comment]
That’s an odd one – only shows in some environments (Chrome), not others (CoreText).

**Comment by erniemarch** [comment]
checked in build 2.940. Fixed.
