### ISSUE TITLE
top of '4' in both roman and italic not catching zone?

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-serif-pro#55]
top of '4' in both roman and italic may not be catching on alignment zone; seems short in many of the waterfall dumps. Please check.

**Comment by frankrolf** [comment]
All iterations of the number 4 were clearly within alignment zones. I brought the tops all a bit higher (within the top third of the respective zone), so the overshoot is enforced instead rather than suppressed.

**Comment by erniemarch** [comment]
checked in build 2.940. Fixed.
