### ISSUE TITLE
Derived glyphs have different advance width than their bases.

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-serif-pro#56]
These may be legitimate, depending on the design but please check.

SourceSerifPro-Black.otf
7 derived glyph(s) have a different advance width than their bases
Hbar.sc
   -11 than H.sc
Uhorn.sc
   -23 than U.sc
uni1EE8.sc
   -23 than U.sc
uni1EEA.sc
   -23 than U.sc
uni1EEC.sc
   -23 than U.sc
uni1EEE.sc
   -23 than U.sc
uni1EF0.sc
   -23 than U.sc

SourceSerifPro-BlackIt.otf
11 derived glyph(s) have a different advance width than their bases
uni02C9 (MODIFIER LETTER MACRON)
   -18 than macron
uni040E (CYRILLIC CAPITAL LETTER SHORT U)
   -11 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni0453 (CYRILLIC SMALL LETTER GJE)
   +12 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +5 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   +1 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +7 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE)
   -19 than uni0436 (CYRILLIC SMALL LETTER ZHE)
uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON)
   -11 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE)
   -11 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni2215 (DIVISION SLASH)
   +285 than fraction
uni2219 (BULLET OPERATOR)
   +240 than periodcentered

SourceSerifPro-Bold.otf
7 derived glyph(s) have a different advance width than their bases
Hbar.sc
   -11 than H.sc
Uhorn.sc
   -23 than U.sc
uni1EE8.sc
   -23 than U.sc
uni1EEA.sc
   -23 than U.sc
uni1EEC.sc
   -23 than U.sc
uni1EEE.sc
   -23 than U.sc
uni1EF0.sc
   -23 than U.sc

SourceSerifPro-BoldIt.otf
13 derived glyph(s) have a different advance width than their bases
figuredash
   -4 than one
uni02C9 (MODIFIER LETTER MACRON)
   -40 than macron
uni040E (CYRILLIC CAPITAL LETTER SHORT U)
   -18 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni0453 (CYRILLIC SMALL LETTER GJE)
   +6 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +11 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   -2 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +7 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE)
   -14 than uni0436 (CYRILLIC SMALL LETTER ZHE)
uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON)
   -18 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE)
   -18 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni2007 (FIGURE SPACE)
   -4 than one
uni2215 (DIVISION SLASH)
   +297 than fraction
uni2219 (BULLET OPERATOR)
   +237 than periodcentered

SourceSerifPro-ExtraLight.otf
8 derived glyph(s) have a different advance width than their bases
Hbar
   +1 than H
Hbar.sc
   -13 than H.sc
Uhorn.sc
   -13 than U.sc
uni1EE8.sc
   -13 than U.sc
uni1EEA.sc
   -13 than U.sc
uni1EEC.sc
   -13 than U.sc
uni1EEE.sc
   -13 than U.sc
uni1EF0.sc
   -13 than U.sc

SourceSerifPro-ExtraLightIt.otf
9 derived glyph(s) have a different advance width than their bases
figuredash
   -20 than one
uni02C9 (MODIFIER LETTER MACRON)
   -48 than macron
uni0453 (CYRILLIC SMALL LETTER GJE)
   +10 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +13 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   -2 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +6 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni2007 (FIGURE SPACE)
   -13 than one
uni2215 (DIVISION SLASH)
   +265 than fraction
uni2219 (BULLET OPERATOR)
   +240 than periodcentered

SourceSerifPro-It.otf
12 derived glyph(s) have a different advance width than their bases
figuredash
   -13 than one
uni02C9 (MODIFIER LETTER MACRON)
   -96 than macron
uni040E (CYRILLIC CAPITAL LETTER SHORT U)
   -33 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni0453 (CYRILLIC SMALL LETTER GJE)
   -9 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +28 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   -12 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +5 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON)
   -33 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE)
   -33 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni2007 (FIGURE SPACE)
   -13 than one
uni2215 (DIVISION SLASH)
   +329 than fraction
uni2219 (BULLET OPERATOR)
   +230 than periodcentered

SourceSerifPro-Light.otf
8 derived glyph(s) have a different advance width than their bases
Hbar
   +1 than H
Hbar.sc
   -13 than H.sc
Uhorn.sc
   -18 than U.sc
uni1EE8.sc
   -18 than U.sc
uni1EEA.sc
   -18 than U.sc
uni1EEC.sc
   -18 than U.sc
uni1EEE.sc
   -18 than U.sc
uni1EF0.sc
   -18 than U.sc

SourceSerifPro-LightIt.otf
12 derived glyph(s) have a different advance width than their bases
figuredash
   -17 than one
uni02C9 (MODIFIER LETTER MACRON)
   -68 than macron
uni040E (CYRILLIC CAPITAL LETTER SHORT U)
   -14 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni0453 (CYRILLIC SMALL LETTER GJE)
   +1 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +20 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   -7 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +6 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON)
   -14 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE)
   -14 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni2007 (FIGURE SPACE)
   -13 than one
uni2215 (DIVISION SLASH)
   +291 than fraction
uni2219 (BULLET OPERATOR)
   +236 than periodcentered

SourceSerifPro-Regular.otf
7 derived glyph(s) have a different advance width than their bases
Hbar.sc
   -12 than H.sc
Uhorn.sc
   -23 than U.sc
uni1EE8.sc
   -23 than U.sc
uni1EEA.sc
   -23 than U.sc
uni1EEC.sc
   -23 than U.sc
uni1EEE.sc
   -23 than U.sc
uni1EF0.sc
   -23 than U.sc

SourceSerifPro-Semibold.otf
7 derived glyph(s) have a different advance width than their bases
Hbar.sc
   -12 than H.sc
Uhorn.sc
   -23 than U.sc
uni1EE8.sc
   -23 than U.sc
uni1EEA.sc
   -23 than U.sc
uni1EEC.sc
   -23 than U.sc
uni1EEE.sc
   -23 than U.sc
uni1EF0.sc
   -23 than U.sc

SourceSerifPro-SemiboldIt.otf
13 derived glyph(s) have a different advance width than their bases
figuredash
   -8 than one
uni02C9 (MODIFIER LETTER MACRON)
   -68 than macron
uni040E (CYRILLIC CAPITAL LETTER SHORT U)
   -25 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni0453 (CYRILLIC SMALL LETTER GJE)
   -2 than uni0433 (CYRILLIC SMALL LETTER GHE)
uni045C (CYRILLIC SMALL LETTER KJE)
   +19 than uni043A (CYRILLIC SMALL LETTER KA)
uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER)
   -7 than uni0417 (CYRILLIC CAPITAL LETTER ZE)
uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER)
   +5 than uni0437 (CYRILLIC SMALL LETTER ZE)
uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE)
   -7 than uni0436 (CYRILLIC SMALL LETTER ZHE)
uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON)
   -25 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE)
   -25 than uni0423 (CYRILLIC CAPITAL LETTER U)
uni2007 (FIGURE SPACE)
   -8 than one
uni2215 (DIVISION SLASH)
   +313 than fraction
uni2219 (BULLET OPERATOR)
   +233 than periodcentered

**Comment by frankrolf** [comment]
Thanks Ernie! Here is my summary:

## SourceSerifPro-ExtraLight.otf
8 derived glyph(s) have a different advance width than their bases
* Hbar +1 than H ✔
* Hbar.sc -13 than H.sc ✔
* Uhorn.sc -13 than U.sc ✔
* uni1EE8.sc -13 than U.sc ✔
* uni1EEA.sc -13 than U.sc ✔
* uni1EEC.sc -13 than U.sc ✔
* uni1EEE.sc -13 than U.sc ✔
* uni1EF0.sc -13 than U.sc ✔

## SourceSerifPro-Light.otf
8 derived glyph(s) have a different advance width than their bases
* Hbar +1 than H ✔
* Hbar.sc -13 than H.sc ✔
* Uhorn.sc -18 than U.sc ✔
* uni1EE8.sc -18 than U.sc ✔
* uni1EEA.sc -18 than U.sc ✔
* uni1EEC.sc -18 than U.sc ✔
* uni1EEE.sc -18 than U.sc ✔
* uni1EF0.sc -18 than U.sc ✔

## SourceSerifPro-Regular.otf
7 derived glyph(s) have a different advance width than their bases
* Hbar.sc -12 than H.sc ✔
* Uhorn.sc -23 than U.sc ✔
* uni1EE8.sc -23 than U.sc ✔
* uni1EEA.sc -23 than U.sc ✔
* uni1EEC.sc -23 than U.sc ✔
* uni1EEE.sc -23 than U.sc ✔
* uni1EF0.sc -23 than U.sc ✔

## SourceSerifPro-Semibold.otf
7 derived glyph(s) have a different advance width than their bases
* Hbar.sc -12 than H.sc ✔
* Uhorn.sc -23 than U.sc ✔
* uni1EE8.sc -23 than U.sc ✔
* uni1EEA.sc -23 than U.sc ✔
* uni1EEC.sc -23 than U.sc ✔
* uni1EEE.sc -23 than U.sc ✔
* uni1EF0.sc -23 than U.sc ✔

## SourceSerifPro-Bold.otf
7 derived glyph(s) have a different advance width than their bases
* Hbar.sc -11 than H.sc ✔
* Uhorn.sc -23 than U.sc ✔
* uni1EE8.sc -23 than U.sc ✔
* uni1EEA.sc -23 than U.sc ✔
* uni1EEC.sc -23 than U.sc ✔
* uni1EEE.sc -23 than U.sc ✔
* uni1EF0.sc -23 than U.sc ✔

## SourceSerifPro-Black.otf
7 derived glyph(s) have a different advance width than their bases
* Hbar.sc -11 than H.sc ✔
* Uhorn.sc -23 than U.sc ✔
* uni1EE8.sc -23 than U.sc ✔
* uni1EEA.sc -23 than U.sc ✔
* uni1EEC.sc -23 than U.sc ✔
* uni1EEE.sc -23 than U.sc ✔
* uni1EF0.sc -23 than U.sc ✔

Thanks for those finds in the Roman small caps. I assume this has to do with a sidebearing-scaling operation.

-----

## SourceSerifPro-ExtraLightIt.otf
9 derived glyph(s) have a different advance width than their bases
* figuredash -20 than one ✔
* uni02C9 (MODIFIER LETTER MACRON) -48 than macron ✘   
Deliberate. IMO modifier letters have a different use than spacing accents. See also here:
https://github.com/productiontype/Spectral/issues/13  
https://github.com/productiontype/Spectral/issues/14  
In fact, I’ll take this opportunity to re-space some of the modifiers in the Roman.
* uni0453 (CYRILLIC SMALL LETTER GJE) +10 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +13 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) -2 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +6 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni2007 (FIGURE SPACE) -13 than one ✔
* uni2215 (DIVISION SLASH) +265 than fraction ✘  
Deliberate.  
I spaced the division slash so it can be used for a setting like 1∕2, while the fraction slash can be used with numerators and denominators (if a frac feature is really not available)
* uni2219 (BULLET OPERATOR) +240 than periodcentered ✔  
This was deliberate. I was thinking the bullet operator (mathematical) should have the same width as tabular figures. 
However I checked other fonts on my system and almost every example ignores this theory, so I unified the bulletoperators with the periodcentereds (and the Romans).


## SourceSerifPro-LightIt.otf
12 derived glyph(s) have a different advance width than their bases
* figuredash -17 than one ✔
* uni02C9 (MODIFIER LETTER MACRON) -68 than macron ✘ (see above)
* uni040E (CYRILLIC CAPITAL LETTER SHORT U) -14 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni0453 (CYRILLIC SMALL LETTER GJE) +1 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +20 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) -7 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +6 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON) -14 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE) -14 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni2007 (FIGURE SPACE) -13 than one ✔
* uni2215 (DIVISION SLASH) +291 than fraction ✘ (see above)
* uni2219 (BULLET OPERATOR) +236 than periodcentered ✔  

## SourceSerifPro-It.otf
12 derived glyph(s) have a different advance width than their bases
* figuredash -13 than one ✔
* uni02C9 (MODIFIER LETTER MACRON) -96 than macron ✘ (see above)
* uni040E (CYRILLIC CAPITAL LETTER SHORT U) -33 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni0453 (CYRILLIC SMALL LETTER GJE) -9 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +28 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) -12 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +5 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON) -33 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE) -33 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni2007 (FIGURE SPACE) -13 than one ✔
* uni2215 (DIVISION SLASH) +329 than fraction ✘ (see above)
* uni2219 (BULLET OPERATOR) +230 than periodcentered ✔

## SourceSerifPro-SemiboldIt.otf
13 derived glyph(s) have a different advance width than their bases
* figuredash -8 than one ✔
* uni02C9 (MODIFIER LETTER MACRON) -68 than macron ✘ (see above)
* uni040E (CYRILLIC CAPITAL LETTER SHORT U) -25 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni0453 (CYRILLIC SMALL LETTER GJE) -2 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +19 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) -7 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +5 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE) -7 than uni0436 (CYRILLIC SMALL LETTER ZHE) ✔
* uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON) -25 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE) -25 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni2007 (FIGURE SPACE) -8 than one ✔
* uni2215 (DIVISION SLASH) +313 than fraction ✘ (see above)
* uni2219 (BULLET OPERATOR) +233 than periodcentered ✔

## SourceSerifPro-BoldIt.otf
13 derived glyph(s) have a different advance width than their bases
* figuredash -4 than one ✔
* uni02C9 (MODIFIER LETTER MACRON) -40 than macron ✘ (see above)
* uni040E (CYRILLIC CAPITAL LETTER SHORT U) -18 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni0453 (CYRILLIC SMALL LETTER GJE) +6 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +11 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) -2 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +7 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE) -14 than uni0436 (CYRILLIC SMALL LETTER ZHE) ✔
* uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON) -18 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE) -18 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni2007 (FIGURE SPACE) -4 than one ✔
* uni2215 (DIVISION SLASH) +297 than fraction ✘ (see above)
* uni2219 (BULLET OPERATOR) +237 than periodcentered ✔

## SourceSerifPro-BlackIt.otf
11 derived glyph(s) have a different advance width than their bases
* uni02C9 (MODIFIER LETTER MACRON) -18 than macron ✘ (see above)
* uni040E (CYRILLIC CAPITAL LETTER SHORT U) -11 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni0453 (CYRILLIC SMALL LETTER GJE) +12 than uni0433 (CYRILLIC SMALL LETTER GHE) ✔
* uni045C (CYRILLIC SMALL LETTER KJE) +5 than uni043A (CYRILLIC SMALL LETTER KA) ✔
* uni0498 (CYRILLIC CAPITAL LETTER ZE WITH DESCENDER) +1 than uni0417 (CYRILLIC CAPITAL LETTER ZE) ✔
* uni0499 (CYRILLIC SMALL LETTER ZE WITH DESCENDER) +7 than uni0437 (CYRILLIC SMALL LETTER ZE) ✔
* uni04C2 (CYRILLIC SMALL LETTER ZHE WITH BREVE) -19 than uni0436 (CYRILLIC SMALL LETTER ZHE) ✔
* uni04EE (CYRILLIC CAPITAL LETTER U WITH MACRON) -11 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni04F2 (CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE) -11 than uni0423 (CYRILLIC CAPITAL LETTER U) ✔
* uni2215 (DIVISION SLASH) +285 than fraction ✘ (see above) 
* uni2219 (BULLET OPERATOR) +240 than periodcentered ✔

**Comment by erniemarch** [comment]
checked in build 2.940. Fixed.
