### ISSUE TITLE
Greek lowercase chi

### ISSUE THREAD

**Issue by AshtarBalynestjar** [adobe-fonts/source-serif-pro#59]
> Are the terminals in the lowercase chi in the light roman supposed to taper off like this? They don’t seem to match the rest of the styles.
> 
> ![image](https://user-images.githubusercontent.com/30967003/59558675-4b2e8e80-8fac-11e9-83b7-64108a0caa62.png)

**Comment by frankrolf** [comment]
Ugh. They are not – that’s an interpolation error. Thanks for noticing!

**Comment by frankrolf** [comment]
This has been resolved with the 3.001 rebuild.
