### ISSUE TITLE
Rendering bug with LibreOffice

### ISSUE THREAD

**Issue by Elendil03** [adobe-fonts/source-serif-pro#62]
I'm using Windows 10 64X, LibreOffice 6.2.4.2 and Source Serif Pro 3.0 otf.

When I enter text, I get a very weird rendering with OpenGL turned off (as my laptop's video card seems to be on the OpenGL "blacklist" which stops OpenGL from rendering LibreOffice on specific video cards). This for good reason: the letters appear really unclean when I override this blacklisting through the options.
![a](https://user-images.githubusercontent.com/51972670/59806084-835b0780-92f3-11e9-91df-ca68d74c54ca.jpg)
![b](https://user-images.githubusercontent.com/51972670/59806088-8655f800-92f3-11e9-8783-f82874d668c3.jpg)
On the other hand, with OpenGL turned off, the rendering becomes a true eyesore when zoomed out (equivalent to smaller font sizes). Notice the thin lines and the crooked upper part of the t letters.
![c](https://user-images.githubusercontent.com/51972670/59806102-89e97f00-92f3-11e9-97b3-a9562327ac8f.jpg)
Zoomed in (same effect as a larger font size), as opposed to before, it all looks fine.
![d](https://user-images.githubusercontent.com/51972670/59806109-8eae3300-92f3-11e9-8a61-4a9314d8dbbf.jpg)
The older font version (2.0.7 or so) included in LO by standard, though, works fine when rendered without OpenGL. Anti-aliasing is turned on for all of the examples.

Could anyone think of what it is that causes this problem to occur?

**Comment by frankrolf** [comment]
It might be worth trying the TTF files here – however I am not convinced I can help much in this situation.

**Comment by Elendil03** [comment]
I've posted the issue in the German LibreOffice forum. Anyway, the ligatures and Old sytle figures are quite important to me, so I'd rather not use the ttf.

**Comment by frankrolf** [comment]
All OT features (such as old style figures and ligatures) are available both in TTF and OTF font files. There is no functional difference between the OTF and TTF versions except the outline format.

**Comment by Elendil03** [comment]
I would've bet any sum against it, but this actually worked. The look is totally clean now with OpenGL turned off - thank you once more. I know basically nothing about the difference between the two formats, but isn't it strange that one causes so much trouble and the other doesn't?

**Comment by frankrolf** [comment]
Glad to hear it!
It might be strange, but such are the ways of rasterizers. Especially in an office environment, TTFs sometimes are the better choice.

**Comment by Elendil03** [comment]
Let me ask one last questions: In which case would the use of otf files be favorable?

**Comment by frankrolf** [comment]
In my opinion, cubic curves (the ones used in CFF-flavored font formats such as OTF) are favorable in the following scenarios:
- in many design applications, such as InDesign
- anywhere file size is a concern
- anywhere a font is converted to outlines

In short: it’s good to have two options.
