### ISSUE TITLE
Publish version 3 to npm

### ISSUE THREAD

**Issue by akrawitz** [adobe-fonts/source-serif-pro#65]
Could you please publish version 3 to npm:
https://www.npmjs.com/package/source-serif-pro

Thank you for a wonderful font! I'm excited for the new Greek italics!

**Comment by frankrolf** [comment]
I don’t know how to do that. Do you think you could help?

**Comment by akrawitz** [comment]
If you have Node installed and you have an npmjs.com account, then I believe you would just need to run `npm publish` in your local directory for the repo. However, it looks like @miguelsousa was the one who published it previously, so perhaps the easiest solution would be to have him do it again.

**Comment by frankrolf** [comment]
@miguelsousa walked me through the process, and I just published version 3 on npm! Enjoy! :-)

**Comment by akrawitz** [comment]
Thank you for such a quick response, and thank you again for the beautiful fonts!
