### ISSUE TITLE
Source serif pro don't show capital letter i in PDF created with Adobe

### ISSUE THREAD

**Issue by Isajica** [adobe-fonts/source-serif-pro#68]
WORD:
![image](https://user-images.githubusercontent.com/61019637/74453195-5b23a880-4e82-11ea-805a-31fe0c515aa1.png)
PDF created with Adobe:
![image](https://user-images.githubusercontent.com/61019637/74453969-780cab80-4e83-11ea-96cc-8b7b1b22c710.png)

**Comment by frankrolf** [comment]
Would you mind elaborating on the meaning of “with Adobe”? Adobe PDF printer?
Also, which versions of Word and “Adobe”?

**Comment by Isajica** [comment]
![image](https://user-images.githubusercontent.com/61019637/74466035-c4151b80-4e96-11ea-89dd-52cdf73c72ce.png)

**Comment by frankrolf** [comment]
Thank you.
There was a similar issue a while ago (#44) – to make sure we are not analyzing the same problem, I’d like to ask you the following:

- please make sure you use the latest versions of the fonts (available here: https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.001R)
- if you use TTF fonts, please try using OTF fonts instead

I hope this solves the problem, if it does, please report back here.

**Comment by Isajica** [comment]
Thank you for the beautiful font.
It didn't solve the problem.

**Comment by erniemarch** [comment]
I have been unable to reproduce this. I tried with both the OTF and the TTF versions. Windows 10, Word/Office version 20. Every PDF export/save I tried produced an intact output file with not missing glyphs.
