### ISSUE TITLE
Source Serif Pro's uppercase glyphs failed to be textsuperscript while being specified in XeLaTeX.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-serif-pro#7]
For example: if I use Georgia or other fonts, it shows \textsuperscript like this:
![image](https://cloud.githubusercontent.com/assets/3164826/5531689/0b901110-89ec-11e4-9203-ad1db757c52e.png)

But if I use Source Serif Pro, it shows like this with \textsuperscript failed-to-apply:
![image](https://cloud.githubusercontent.com/assets/3164826/5531700/234c6c9a-89ec-11e4-9f7b-bf5e24612a43.png)

**Comment by dag** [comment]
FWIW XeLaTeX doesn't do this (for me and/or any longer anyway, with TeX Live 2015) by default; I have to load the `realscripts` package which is from 2013, suggesting it was required back then as well. Are you loading that, directly or indirectly, perhaps? If that is the case, you'll have access to the `\fakesuperscript` macro that skips the `sups` OT feature (run `texdoc realscripts` for documentation).

As for Western use cases, I'm not sure it's done very frequently but it *is* possible to configure LaTeX packages like biblatex to put citations in superscripts, *and* to label the citations based on author/year which means it will typically contain upper-case letters:

> For example, instead of “Jones 1995” this style would use the label “[Jon95]”. “Jones and Williams 1986” would be rendered as “[JW86]”.

But typically this style will only be used in-line, and only a numeric style for superscripts.

I thought of Wikipedia as another example but upon looking for confirmation I realized it only uses lower-case superscripts, at least for the common ones like `[citation needed]`.

**Comment by ShikiSuen** [comment]
@dag Thanks to your suggestion. I will use \fakesuperscript in lieu of this issue request. Over.

**Comment by frankrolf** [comment]
FYI: The next release of Source Serif Pro will include uppercase superiors & brackets.

**Comment by frankrolf** [comment]
@ShikiSuen [Source Serif Version 2.0](https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.000R) has a full set of superior caps and also superior brackets.
Your issue even made it into the blog post! 
http://blog.typekit.com/2017/01/10/introducing-source-serif-2-0/
