### ISSUE TITLE
Source Serif Pro variable font missing spaces in Chrome/Edge (Mac OS)

### ISSUE THREAD

**Issue by starzonmyarmz** [adobe-fonts/source-serif-pro#70]
I'm noticing that the variable font for Source Serif Pro is missing the "space" character or isn't rendering (or something...) in the Chrome engine. I'm using the latest version from the `master` branch of `SourceSerifVariable-Roman.otf.woff2` and `SourceSerifVariable-Italic.otf.woff2`. I was wondering if it had something to do with how I was implementing it on my site, but I'm also seeing it on https://v-fonts.com/fonts/source-serif-variable (where you can test it yourself).

Thoughts?

**Comment by frankrolf** [comment]
This is the same issue as https://github.com/adobe-fonts/source-sans-pro/issues/188 – a Chrome bug. See more: https://bugs.chromium.org/p/chromium/issues/detail?id=1054371

**Comment by starzonmyarmz** [comment]
Thanks, and sorry for the extra noise!

**Comment by frankrolf** [comment]
No worries! :-)
