### ISSUE TITLE
The website is broken

### ISSUE THREAD

**Issue by stone-zeng** [adobe-fonts/source-serif-pro#75]
The website (<https://adobe-fonts.github.io/source-serif-pro>) for Source Serif Pro can't be opened (404), but for Source Sans/Code Pro it's OK. Please check it. Thank you!

**Comment by frankrolf** [comment]
Thanks for the note. This is an unintended consequence of renaming the main branch – I’ll fix it!

**Comment by davelab6** [comment]
Ping :)

**Comment by frankrolf** [comment]
This needs to be fixed on GitHub’s end. Apparently Github pages relies on a `master` branch to exist, while the branch name itself is discouraged.

**Comment by cjchapman** [comment]
There's now a GitHub settings option to change the branch from which it publishes, which I've done. You should be able to see it now.

**Comment by frankrolf** [comment]
Thanks @cjchapman! 😎

**Comment by davelab6** [comment]
🙏🙏🙏

**Comment by stone-zeng** [comment]
Thanks~
